<?
 return [
     "1"=>[
        "login"=>"igor",
        "pass"=>"1234",
        "file"=>"tasks.txt",
     ],
     "2"=>[
      "login"=>"user",
      "pass"=>"4321",
      "file"=>"taskstwo.txt",
     ],
     "3"=>[
      "login"=>"ivan",
      "pass"=>"2468",
      "file"=>"tasksthree.txt",
     ],
     "4"=>[
      "login"=>"admin",
      "pass"=>"2468",
      "file"=>"tasksthree.txt",
     ],
];